Tree/Models/ErrorViewModel.cs
using System;

namespace Tree.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tree/Models/Node.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tree.Models
{
    public class Node
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public int? ParentNodeId { get; set; }

        public Node ParentNode { get; set; }
    }
}

Tree/ViewModels/ErrorViewModel.cs
using System;

namespace Tree.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tree/ViewModels/NodeBaseViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tree.ViewModels
{
    public class NodeBaseViewModel
    {
        [Required]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        public IEnumerable<SelectListItem> NodeList { get; set; }
    }
}

Tree/ViewModels/NodeCreateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tree.ViewModels
{
    public class NodeCreateViewModel
    {
        [Required]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Parent node")]
        public int? ParentNodeId { get; set; }

        public IEnumerable<SelectListItem> NodeList { get; set; }

    }
}

Tree/ViewModels/NodeUpdateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tree.ViewModels
{
    public class NodeUpdateViewModel : NodeBaseViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Parent node")]
        public int? ParentNodeId { get; set; }
    }
}

Tree/ViewModels/NodeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tree.Models;

namespace Tree.ViewModels
{
    public class NodeViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int? ParentNodeId { get; set; }

        public List<NodeViewModel> ChildNodes { get; set; }

        public NodeViewModel(Node node)
        {
            this.Id = node.Id;
            this.Name = node.Name;
            this.ParentNodeId = node.ParentNodeId;
        }

        public void SetChilds(List<Node> nodes)
        {
            this.ChildNodes = nodes.Where(n => n.ParentNodeId == this.Id).Select(n => new NodeViewModel(n)).ToList();
            this.ChildNodes.ForEach(child => child.SetChilds(nodes));
        }
    }
}

Tree/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tree.ViewModels;

namespace Tree.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tree/Controllers/NodeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tree.Facades;
using Tree.Utilities.Extensions;
using Tree.ViewModels;

namespace Tree.Controllers
{
    [Authorize]
    public class NodeController : Controller
    {
        private readonly NodeFacade nodeFacade;

        public NodeController(NodeFacade nodeFacade)
        {
            this.nodeFacade = nodeFacade;
        }

        public IActionResult Index()
        {
            var count = this.nodeFacade.GetNodesCount();

            return View(count > 0);
        }

        public IActionResult GetMainNodeWithChilds()
        {
            IActionResult result = NotFound();

            var nodeVm = this.nodeFacade.GetMainNodeWithChilds();

            if (nodeVm != null)
            {
                result = Json(new { data = nodeVm });
            }

            return result;
        }

        public IActionResult Create(int id)
        {
            var vm = this.nodeFacade.GetCreateNodeItem(id);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(int id, NodeCreateViewModel nodeVm)
        {
            IActionResult result = null;

            if (ModelState.IsValid)
            {
                this.nodeFacade.CreateNode(id, nodeVm);

                result = RedirectToAction(nameof(Index));
            }
            else
            {
                nodeVm.NodeList = this.nodeFacade.GetNodeSelectList(id);
                
                result = View(nodeVm);
            }

            return result;
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = this.nodeFacade.DeleteItem(id);

            return Json(new { success = isDeleted });
        }

        public IActionResult Edit(int id)
        {
            var nodeVm = this.nodeFacade.GetUpdateNodeItem(id);

            return nodeVm != null ? View(nodeVm) : RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, NodeUpdateViewModel nodeVm)
        {
            IActionResult result = null;

            if (ModelState.IsValid)
            {
                this.nodeFacade.UpdateNode(nodeVm);

                result = RedirectToAction(nameof(Index));
            }
            else
            {
                nodeVm.NodeList = this.nodeFacade.GetEditNodeSelectList(id, nodeVm.ParentNodeId == 0);

                result = View(nodeVm);
            }

            return result;
        }
    }
}

Tree/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tree/Views/Node/Create.cshtml
@model Tree.ViewModels.NodeCreateViewModel


@{
    ViewData["Title"] = "New node";
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<h1>New node</h1>

<form method="post" novalidate="novalidate">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-8 pt-4">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" maxlength="50" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ParentNodeId"></label>
                </div>
                <div class="col-8">
                    @Html.DropDownListFor(m => m.ParentNodeId, Model.NodeList,
                   new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary form-control">Save</button>
                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success form-control">Back</a>
                </div>
            </div>

        </div>
    </div>
</form>

Tree/Views/Node/Edit.cshtml
@model Tree.ViewModels.NodeUpdateViewModel


@{
    ViewData["Title"] = "New node";
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<h1>Edit node</h1>

<form method="post" novalidate="novalidate">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="Id" hidden />

        <div class="col-8 pt-4">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" maxlength="50" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ParentNodeId"></label>
                </div>
                <div class="col-8">
                    @Html.DropDownListFor(m => m.ParentNodeId, Model.NodeList, "Select parent node",
                   new { @class = "form-control" })
                    <span asp-validation-for="ParentNodeId" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary form-control">Save</button>
                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success form-control">Back</a>
                </div>
            </div>

        </div>
    </div>
</form>

Tree/Views/Node/Index.cshtml
@model bool

@{
    ViewData["Title"] = "Tree";

}

@if (!Model)
{
    <a class="btn btn-primary" asp-area="" asp-controller="Node" asp-action="Create">New</a>
}


<div id="nodes"></div>


@section Scripts {
    <script src="~/js/node.js"></script>
}

Tree/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity


@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tree</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tree</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Node" asp-action="Index">Tree</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tree - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>